apiVersion: v1
kind: Service
metadata:
  name: bookinfo-dev-ratings
  namespace: student4-bookinfo-dev
spec:
  type: {{ .Values.ingress.serviceType }}
  ports:
  - port: {{ .Values.ratings.port }}
  selector:
    app: bookinfo-dev-ratings
